# Generated by Django 5.2.7 on 2025-10-31 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('satisfaction', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('notes', models.TextField()),
                ('image_url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='users.user'
                    ),
                ),
                (
                    'weather_data',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='weather.weatherdata',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Diary',
                'verbose_name_plural': 'Diaries',
                'db_table': 'diary',
            },
        ),
    ]
