# Generated by Django 5.2.7 on 2025-10-31 05:44

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AiModelSettings',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('temperature_max', models.FloatField()),
                ('temperature_min', models.FloatField()),
                (
                    'humidity_max',
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ]
                    ),
                ),
                (
                    'humidity_min',
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ]
                    ),
                ),
                ('weather_condition', models.CharField(blank=True, max_length=100)),
                ('category_combo', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ai_model_settings',
                'indexes': [
                    models.Index(
                        fields=['active'], name='ai_model_se_active_6495a8_idx'
                    ),
                    models.Index(
                        fields=['weather_condition'],
                        name='ai_model_se_weather_efdc3f_idx',
                    ),
                    models.Index(
                        fields=['temperature_max', 'temperature_min'],
                        name='ai_model_se_tempera_920c8d_idx',
                    ),
                    models.Index(
                        fields=['humidity_max', 'humidity_min'],
                        name='ai_model_se_humidit_0536b7_idx',
                    ),
                ],
                'constraints': [
                    models.CheckConstraint(
                        condition=models.Q(
                            ('temperature_min__lte', models.F('temperature_max'))
                        ),
                        name='ck_temp_min_le_max',
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ('humidity_min__lte', models.F('humidity_max'))
                        ),
                        name='ck_humidity_min_le_max',
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name='AiChatLogs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                (
                    'session_id',
                    models.CharField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        max_length=200,
                    ),
                ),
                ('user_question', models.TextField()),
                ('ai_answer', models.TextField()),
                ('context', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                (
                    'user_id',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='ai_chat_logs',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'ai_model_setting_id',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='ai_chat_logs',
                        to='chatbot.aimodelsettings',
                    ),
                ),
            ],
            options={
                'db_table': 'ai_chat_logs',
                'indexes': [
                    models.Index(
                        fields=['created_at'], name='ai_chat_log_created_583262_idx'
                    ),
                    models.Index(
                        fields=['session_id', 'created_at'],
                        name='ai_chat_log_session_94304c_idx',
                    ),
                    models.Index(
                        fields=['user_id', 'created_at'],
                        name='ai_chat_log_user_id_0c7b89_idx',
                    ),
                ],
            },
        ),
    ]
