# Generated by Django 5.2.7 on 2025-10-31 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherDailySummary',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('date', models.DateField()),
                (
                    'temperature_min',
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    'temperature_max',
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ('humidity_min', models.PositiveSmallIntegerField()),
                ('humidity_max', models.PositiveSmallIntegerField()),
                ('dominant_condition', models.CharField(max_length=100)),
                ('provider', models.CharField(default='OpenWeather', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'location',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='weather_daily_summary',
                        to='locations.location',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Weather Daily Summary',
                'verbose_name_plural': 'Weather Daily Summaries',
                'db_table': 'weather_daily_summary',
                'indexes': [
                    models.Index(
                        fields=['location'], name='weather_dai_locatio_8449be_idx'
                    ),
                    models.Index(fields=['date'], name='weather_dai_date_282750_idx'),
                ],
                'constraints': [
                    models.UniqueConstraint(
                        fields=('location', 'date'), name='uq_location_date'
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('provider', models.CharField(default='OpenWeather', max_length=50)),
                (
                    'weather_type',
                    models.CharField(
                        choices=[('current', 'Current'), ('forecast', 'Forecast')],
                        default='current',
                        max_length=20,
                    ),
                ),
                ('base_time', models.DateTimeField()),
                ('valid_time', models.DateTimeField()),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=5)),
                ('feels_like', models.DecimalField(decimal_places=2, max_digits=5)),
                ('humidity', models.PositiveSmallIntegerField()),
                (
                    'rain_probability',
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    'rain_volume',
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ('wind_speed', models.DecimalField(decimal_places=2, max_digits=5)),
                ('icon', models.CharField(blank=True, max_length=10, null=True)),
                ('condition', models.CharField(max_length=100)),
                ('raw_payload', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'location',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='weather_data',
                        to='locations.location',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Weather Data',
                'verbose_name_plural': 'Weather Data',
                'db_table': 'weather_data',
                'indexes': [
                    models.Index(
                        fields=['location'], name='weather_dat_locatio_7c8b74_idx'
                    ),
                    models.Index(
                        fields=['valid_time'], name='weather_dat_valid_t_0fbceb_idx'
                    ),
                    models.Index(
                        fields=['weather_type'], name='weather_dat_weather_d4a7b1_idx'
                    ),
                ],
                'constraints': [
                    models.UniqueConstraint(
                        fields=('location', 'provider', 'weather_type', 'valid_time'),
                        name='uq_location_provider_type_validtime',
                    )
                ],
            },
        ),
    ]
