# Generated by Django 5.2.7 on 2025-10-31 05:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('city', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '위치',
                'verbose_name_plural': '위치 목록',
                'db_table': 'locations',
                'indexes': [
                    models.Index(fields=['city'], name='locations_city_278550_idx'),
                    models.Index(
                        fields=['district'], name='locations_distric_c06b75_idx'
                    ),
                    models.Index(
                        fields=['latitude', 'longitude'],
                        name='locations_latitud_4052bd_idx',
                    ),
                ],
                'constraints': [
                    models.UniqueConstraint(
                        fields=('latitude', 'longitude'),
                        name='unique_latitude_longitude',
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name='FavoriteLocation',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('alias', models.CharField(blank=True, max_length=100, null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='favorite_locations',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'location',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='favorited_by',
                        to='locations.location',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Favorite Location',
                'verbose_name_plural': 'Favorite Locations',
                'db_table': 'favorite_locations',
                'constraints': [
                    models.UniqueConstraint(
                        fields=('user', 'location'), name='uq_user_location'
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(('is_default', True)),
                        fields=('user',),
                        name='uq_user_default_location',
                    ),
                ],
            },
        ),
    ]
